name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build
        run: echo "No build needed for static files"
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: slides/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
